// Archivo Principal del Codigo del Robot, generado por WPILIB. NO MODIFICAR.
/////////////////////////////////////////////////////////////////////////////
// Main file of the Robot Code, generated by WPILIB. DO NOT MODIFY.

package frc.robot;

import edu.wpi.first.wpilibj.RobotBase;

public final class Main {
  private Main() {}

  public static void main(String... args) {
    RobotBase.startRobot(Robot::new);
  }
}
